name: sync-code
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
  watch:
    types: started

jobs:
  sync:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    timeout-minutes: 2
    
    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential git git-core curl wget jq
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        
    - name: Get Code from Private Repository
      run: |
        wget https://raw.githubusercontent.com/okyyds/okyyds/master/yyds.sh
        chomd +x yyds.sh
        ./yyds.sh
        git clone git@github.com:okyyds/yyds.git main
        
    - name: Push to main
      run: |
        echo -e "${{ secrets.GITHUBKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        cd main
        git remote add github "${{ secrets.GITHUBREPO }}"
        git push -u github main >/dev/null 2>&1
